### ISSUE TITLE
Not able to add padding

### ISSUE THREAD

**Issue by AndrewPetrovics** [NilsBacke/PHSpeechBubble#2]
Pretty sure it's because the padding argument is looking for a Widget and not an EdgeInsets

**Comment by NilsBacke** [comment]
See #3

**Comment by Vanethos** [comment]
Commenting on this since I added the following on the PR:

The thing is that when you are doing this:

```
Container(
        height: this.height,
        width: this.width,
        padding: this.padding ?? const EdgeInsets.all(8.0),
        child: this.child,
),
```
that `padding` is not a widget. It is a `EdgeInsetsGeometry` that extends the abstract class EdgeInsetsGeometry, hence it is not possible to add a padding widget.

This way we can add the padding the way you intended :D
